######################################################################
# This file was autogenerated by 'configure'. Do not edit it directly!
# Invocation was: ./configure 
######################################################################
PREFIX=/usr/local
######################################################################
SHELL     ?= zsh
PREFIX    ?= /usr/local

CRAM_OPTS ?= -v

PROJECT   ?= $(CURDIR)
BIN       ?= ${PROJECT}/bin
SRC       ?= ${PROJECT}/src
TESTS     ?= ${PROJECT}/tests
TOOLS     ?= ${PROJECT}/tools
TEST      ?= ${PROJECT}/tests

ZSH_VERSION     ?= zsh-5.8
CONTAINER_ROOT  ?= /zunit
USE_CONTAINER   ?= docker
CONTAINER_IMAGE ?= desyncr/zsh-docker-

TARGET     ?= ${BIN}/zunit
SRC        ?= ${SRC}
GLOB       ?= 

LIB      = $(filter-out ${SRC}/zunit.zsh,$(wildcard ${PWD}/src/*.zsh))
COMMANDS = $(sort $(wildcard ${PWD}/src/commands/*.zsh)) 
REPORTS  = $(sort $(wildcard ${PWD}/src/reports/*.zsh))
GLOB    += ${LIB} ${REPORTS} ${COMMANDS} ${SRC}/zunit.zsh

VERSION      ?= develop
VERSION_FILE = ${PROJECT}/VERSION

BANNER_SEP   =$(shell printf '%*s' 70 | tr ' ' '\#')
BANNER_TEXT  =This file was autogenerated by \`make\`. Do not edit it directly!
BANNER       =${BANNER_SEP}\n\# ${BANNER_TEXT}\n${BANNER_SEP}\n

HEADER_TEXT   =\#!/usr/bin/env zsh\n\
\# Antigen: A simple plugin manager for zsh\n\
\# Authors: Shrikant Sharat Kandula\n\
\#          and Contributors <https://github.com/zsh-users/antigen/contributors>\n\
\# Homepage: http://antigen.sharats.me\n\
\# License: MIT License <mitl.sharats.me>\n

define ised
	sed $(1) $(2) > "$(2).1"
	mv "$(2).1" "$(2)"
endef

define isede
	sed -E $(1) $(2) > "$(2).1"
	mv "$(2).1" "$(2)"
endef

.PHONY: itests tests install all

build:
	@echo Building Zunit...
	@mkdir -p ${BIN} 
	@printf "${HEADER_TEXT}" > ${BIN}/zunit
	@echo "${BANNER}" >> ${BIN}/zunit
	@for src in ${GLOB}; do echo "----> $$src"; cat "$$src" | grep -v -e '#\svim.*' -e '^(\s*#.*|\s*)\$$' >> ${TARGET}; done
	@echo "${VERSION}" > ${VERSION_FILE}
	@$(call ised,"s/{{ANTIGEN_VERSION}}/$$(cat ${VERSION_FILE})/",${TARGET})
	@$(call ised,"s/{{ANTIGEN_REVISION}}/$$(git log -n1 --format=%h -- src)/",${TARGET})
	@$(call ised,"s/{{ANTIGEN_REVISION_DATE}}/$$(git log -n1 --format='%ai' -- src)/",${TARGET})
	$(echo Done)
	$(shell ls -sh ${TARGET})

release:
	# Move to release branch
	git checkout develop
	git checkout -b release/${VERSION}
	# Run build and tests
	${MAKE} build tests
	# Update changelog
	${EDITOR} CHANGELOG.md
	# Build release commit
	git add CHANGELOG.md README.mkd ${VERSION_FILE}
	git commit -S -m "Update changelog for ${VERSION}"
	# Update binary artifact
	git add ${TARGET}
	git commit -S -m "Build release ${VERSION}"

publish:
	git push origin release/${VERSION}
	# Merge release branch into develop before deploying

deploy:
	git checkout develop
	git tag -m "Build release ${VERSION}" -s ${VERSION}
	git archive --output=${VERSION}.tar.gz --prefix=antigen-$$(echo ${VERSION}|sed s/v//)/ ${VERSION}
	zcat ${VERSION}.tar.gz | gpg --armor --detach-sign >${VERSION}.tar.gz.sign
	# Verify signature
	zcat ${VERSION}.tar.gz | gpg --verify ${VERSION}.tar.gz.sign -
	# Push upstream
	git push upstream ${VERSION}

.container:
ifeq (${USE_CONTAINER}, docker)
	@docker run --rm --privileged=true -it -v ${PROJECT}:/antigen ${CONTAINER_IMAGE}${ZSH_VERSION} $(shell echo "${COMMAND}" | sed "s|${PROJECT}|${CONTAINER_ROOT}|g")
else ifeq (${USE_CONTAINER}, no)
	${COMMAND}
endif

info:
	@${MAKE} .container COMMAND="sh -c 'cat ${PROJECT}/VERSION; zsh --version; git --version; env'"

itests:
	@${MAKE} tests CRAM_OPTS=-i

tests:
	@${MAKE} .container COMMAND="sh -c 'ZDOTDIR=${TESTS} ANTIGEN=${PROJECT} cram ${CRAM_OPTS} --shell=zsh ${TEST}'"

stats:
	@${MAKE} .container COMMAND="${TOOLS}/stats --zsh zsh --antigen ${PROJECT}"

install:
	install -cv -m755 ${TARGET} ${PREFIX}/bin/zunit

clean:
	rm -rf ${BIN} ${PREFIX}/bin/zunit

install-deps:
	sudo pip install cram=='0.6.*'

all: clean build install
